#!/bin/bash
# hnx - qwerty and left-hand dvorak
# Installed in /usr/local/bin

keyboardstate=

if [ $(setxkbmap -query | grep layout | grep -c us) = 0 ]; then
    keyboardstate=unknown
elif [ $(setxkbmap -query | grep -c variant) = 1 ]; then
    if [ $(setxkbmap -query | grep variant | grep -c dvorak-l) = 1 ]; then
        keyboardstate=dvorak
    else
        keyboardstate=unknown
    fi
else
    keyboardstate=qwerty
fi

case $1 in
"")
    if [ "$keyboardstate" = "dvorak" ]; then
        setxkbmap us
        echo Switched to qwerty keyboard.
    elif [ "$keyboardstate" = "qwerty" ]; then
        setxkbmap us dvorak-l
        echo Switched to left-hand dvorak.
    else
        setxkbmap us
        echo Switched to qwerty keyboard.
    fi
    ;;
v|--query)
    if [ "$keyboardstate" = "dvorak" ]; then
        echo Left-hand dvorak keyboard in use.
    elif [ "$keyboardstate" = "qwerty" ]; then
        echo Qwerty keyboard layout in use.
    else
        echo Unknown keyboard layout.
    fi
    ;;
--help)
    echo "hnx switches between the dvorak left-hand and qwerty keyboards.
Use no option to switch between the keyboards.
Use the v opition to see what keyboard is currantly set.
Check the man page for more information. (some day, fingers crossed)"
    ;;
--version)
    echo hnx version 1.0.1
    ;;
*)
    echo Unknown option, use no option to change keyboards or --help for help.
    ;;
esac
